<!DOCTYPE html>
<html lang="pt">
<head>
<meta charset="utf-8">
<link
	href="http://cdn.fterceiro.pt/library/bootstrap/css/bootstrap.min.css"
	media="screen" rel="stylesheet" type="text/css">
<link href="/css/styles.css" media="screen" rel="stylesheet"
	type="text/css">
</head>
<body>
	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container-fluid">
				<span class="brand">REGISTO DE MANUTENÇÃO CORRECTIVA</span>
			</div>
		</div>
	</div>
	<div class="container">
		<div class="initform" id="initform">
			<div class="container-fluid mywhite">
				<div class="row-fluid">
					<div class="span12">
						<h4 style="text-align: center;">Foi Criado um novo Registo de
							Manutenção Correctiva</h4>
						<div id="content-mail" class="content-mail-body">
							<ul class="thumbnails">
								<li class="span4">
									<div class="thumbnail">
										<img class=""
											src="http://cdn.fterceiro.pt/library/images/web.jpg"
											width="100px" height="100px" alt="WEB">
										<h3>WEB</h3>
										<p>Utilize esta opção para visualizar o Registo de Manutenção</p>
										<a class="btn btn-primary space-bottom-10" href="/index/view/">Visualizar</a>
									</div>
								</li>
								<li class="span4">
									<div class="thumbnail">
										<img src="http://cdn.fterceiro.pt/library/images/pdf.jpg"
											width="100px" height="100px" alt="pdf">
										<h3>PDF</h3>
										<p>Utilize esta opção para fazer um Pdf do Registo de
											Manutenção.</p>
										<a class="btn btn-primary space-bottom-10" href="/index/pdf">Criar
											PDF</a>
									</div>
								</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>
</html>